// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: simpleEnum/simpleEnum.proto

package DataTimepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeekDay int32

const (
	WeekDay_UNDEFINED         WeekDay = 0
	WeekDay_DAY_ONE_MONDAY    WeekDay = 1
	WeekDay_DAY_ONE_TUESDAY   WeekDay = 2
	WeekDay_DAY_ONE_WEDNESDAY WeekDay = 3
	WeekDay_DAY_ONE_THURSDAY  WeekDay = 4
	WeekDay_DAY_ONE_FRIDAY    WeekDay = 5
	WeekDay_DAY_ONE_SATURDAY  WeekDay = 6
	WeekDay_DAY_ONE_SUNDAY    WeekDay = 7
)

// Enum value maps for WeekDay.
var (
	WeekDay_name = map[int32]string{
		0: "UNDEFINED",
		1: "DAY_ONE_MONDAY",
		2: "DAY_ONE_TUESDAY",
		3: "DAY_ONE_WEDNESDAY",
		4: "DAY_ONE_THURSDAY",
		5: "DAY_ONE_FRIDAY",
		6: "DAY_ONE_SATURDAY",
		7: "DAY_ONE_SUNDAY",
	}
	WeekDay_value = map[string]int32{
		"UNDEFINED":         0,
		"DAY_ONE_MONDAY":    1,
		"DAY_ONE_TUESDAY":   2,
		"DAY_ONE_WEDNESDAY": 3,
		"DAY_ONE_THURSDAY":  4,
		"DAY_ONE_FRIDAY":    5,
		"DAY_ONE_SATURDAY":  6,
		"DAY_ONE_SUNDAY":    7,
	}
)

func (x WeekDay) Enum() *WeekDay {
	p := new(WeekDay)
	*p = x
	return p
}

func (x WeekDay) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeekDay) Descriptor() protoreflect.EnumDescriptor {
	return file_simpleEnum_simpleEnum_proto_enumTypes[0].Descriptor()
}

func (WeekDay) Type() protoreflect.EnumType {
	return &file_simpleEnum_simpleEnum_proto_enumTypes[0]
}

func (x WeekDay) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeekDay.Descriptor instead.
func (WeekDay) EnumDescriptor() ([]byte, []int) {
	return file_simpleEnum_simpleEnum_proto_rawDescGZIP(), []int{0}
}

type DateTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Day WeekDay `protobuf:"varint,2,opt,name=day,proto3,enum=dateTime.WeekDay" json:"day,omitempty"`
}

func (x *DateTime) Reset() {
	*x = DateTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpleEnum_simpleEnum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateTime) ProtoMessage() {}

func (x *DateTime) ProtoReflect() protoreflect.Message {
	mi := &file_simpleEnum_simpleEnum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateTime.ProtoReflect.Descriptor instead.
func (*DateTime) Descriptor() ([]byte, []int) {
	return file_simpleEnum_simpleEnum_proto_rawDescGZIP(), []int{0}
}

func (x *DateTime) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DateTime) GetDay() WeekDay {
	if x != nil {
		return x.Day
	}
	return WeekDay_UNDEFINED
}

var File_simpleEnum_simpleEnum_proto protoreflect.FileDescriptor

var file_simpleEnum_simpleEnum_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x2f, 0x73, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x2e, 0x57, 0x65, 0x65, 0x6b,
	0x44, 0x61, 0x79, 0x52, 0x03, 0x64, 0x61, 0x79, 0x2a, 0xac, 0x01, 0x0a, 0x07, 0x57, 0x65, 0x65,
	0x6b, 0x44, 0x61, 0x79, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x44, 0x41, 0x59, 0x5f, 0x4f, 0x4e, 0x45, 0x5f, 0x4d,
	0x4f, 0x4e, 0x44, 0x41, 0x59, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x44, 0x41, 0x59, 0x5f, 0x4f,
	0x4e, 0x45, 0x5f, 0x54, 0x55, 0x45, 0x53, 0x44, 0x41, 0x59, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11,
	0x44, 0x41, 0x59, 0x5f, 0x4f, 0x4e, 0x45, 0x5f, 0x57, 0x45, 0x44, 0x4e, 0x45, 0x53, 0x44, 0x41,
	0x59, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x44, 0x41, 0x59, 0x5f, 0x4f, 0x4e, 0x45, 0x5f, 0x54,
	0x48, 0x55, 0x52, 0x53, 0x44, 0x41, 0x59, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x44, 0x41, 0x59,
	0x5f, 0x4f, 0x4e, 0x45, 0x5f, 0x46, 0x52, 0x49, 0x44, 0x41, 0x59, 0x10, 0x05, 0x12, 0x14, 0x0a,
	0x10, 0x44, 0x41, 0x59, 0x5f, 0x4f, 0x4e, 0x45, 0x5f, 0x53, 0x41, 0x54, 0x55, 0x52, 0x44, 0x41,
	0x59, 0x10, 0x06, 0x12, 0x12, 0x0a, 0x0e, 0x44, 0x41, 0x59, 0x5f, 0x4f, 0x4e, 0x45, 0x5f, 0x53,
	0x55, 0x4e, 0x44, 0x41, 0x59, 0x10, 0x07, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x44, 0x61, 0x74,
	0x61, 0x54, 0x69, 0x6d, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_simpleEnum_simpleEnum_proto_rawDescOnce sync.Once
	file_simpleEnum_simpleEnum_proto_rawDescData = file_simpleEnum_simpleEnum_proto_rawDesc
)

func file_simpleEnum_simpleEnum_proto_rawDescGZIP() []byte {
	file_simpleEnum_simpleEnum_proto_rawDescOnce.Do(func() {
		file_simpleEnum_simpleEnum_proto_rawDescData = protoimpl.X.CompressGZIP(file_simpleEnum_simpleEnum_proto_rawDescData)
	})
	return file_simpleEnum_simpleEnum_proto_rawDescData
}

var file_simpleEnum_simpleEnum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_simpleEnum_simpleEnum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_simpleEnum_simpleEnum_proto_goTypes = []interface{}{
	(WeekDay)(0),     // 0: dateTime.WeekDay
	(*DateTime)(nil), // 1: dateTime.DateTime
}
var file_simpleEnum_simpleEnum_proto_depIdxs = []int32{
	0, // 0: dateTime.DateTime.day:type_name -> dateTime.WeekDay
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_simpleEnum_simpleEnum_proto_init() }
func file_simpleEnum_simpleEnum_proto_init() {
	if File_simpleEnum_simpleEnum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_simpleEnum_simpleEnum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DateTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_simpleEnum_simpleEnum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_simpleEnum_simpleEnum_proto_goTypes,
		DependencyIndexes: file_simpleEnum_simpleEnum_proto_depIdxs,
		EnumInfos:         file_simpleEnum_simpleEnum_proto_enumTypes,
		MessageInfos:      file_simpleEnum_simpleEnum_proto_msgTypes,
	}.Build()
	File_simpleEnum_simpleEnum_proto = out.File
	file_simpleEnum_simpleEnum_proto_rawDesc = nil
	file_simpleEnum_simpleEnum_proto_goTypes = nil
	file_simpleEnum_simpleEnum_proto_depIdxs = nil
}
