package main

import (
	"fmt"
	"log"
	"time"
)

//This function will block for a while

// func main(){
// 	ch := make(chan string)

// 	go func(){
// 		fmt.Println("Goroutine is started...waiting")
// 		time.Sleep(time.Second) //wait for a second
// 		fmt.Println("Goroutine is ended....")

// 		ch <- "Goroutine finished" //unblock
// 		fmt.Println("Goroutine pushed value to channel")
// 	}()

// 	fmt.Println("Main goroutine is waiting for channel to recevie value")
// 	fmt.Println(<- ch) //block
// 	fmt.Println("Main goroutine finished")
// }

//Using Select to prevent blocking
func main() {
	ch := make(chan string)

	go func() {
		fmt.Println("Goroutine is started...waiting")
		time.Sleep(time.Second) //wait for a second
		fmt.Println("Goroutine is ended....")

		ch <- "Goroutine finished" //unblock
		fmt.Println("Goroutine pushed value to channel")
	}()

	//loop to check the blocking state
	for {
		select { //like the switch but for channel
		case value, _ := <-ch: //in this case if the channel is not empty(has value)
			log.Println(value)
			log.Println("Main goroutine is finished")
			return
		default:
			fmt.Println("Waiting...")
			time.Sleep(250 * time.Microsecond) //wait for 0.5s and check again
		}
	}
}

/*
Output : just let us/user know something is happened ,tell them to wait
Waiting...
Goroutine is started...waiting
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Waiting...
Goroutine is ended....
Waiting...
Goroutine pushed value to channel
2021/07/23 16:20:41 Goroutine finished
2021/07/23 16:20:41 Main goroutine is finished
*/
